tasks:
  - name: ensure apt cache is up to date
    action: apt update_cache=yes

  # Ansible requires pscyopg2 and libpq-dev for postgresql_user
  - name: install psycopg2 and libpq-dev
    apt: pkg={{ item }} state=installed
    with_items:
      - python-psycopg2
      - libpq-dev

  - name: Install postgres
    apt: pkg=postgresql state=installed

  - name: ensure postgres is running
    service: name=postgresql enabled=yes state=started

  - name: create postgres user
    postgresql_user: name={{ db_user }} password={{ db_pass }} role_attr_flags=CREATEDB,NOSUPERUSER
    sudo_user: postgres

  - name: create postgres db
    postgresql_db: name={{ db_name }}
